// Curated candidate list for the Popular Plates feature — checked
// periodically against each live state by app/api/cron/check-popular-plates
// and cached in the popular_plates table (never live-checked on a page
// view). Every word here was live-verified at least once (2026-08-16, all
// 9 then-live states) before being added — this list isn't guessed, it's
// the confirmed-real starting set. Expand it by adding a word here; the
// next cron run picks it up automatically.
export type PopularPlateWord = { word: string; category: string };

export const POPULAR_PLATE_WORDS: PopularPlateWord[] = [
  { word: "JESUS", category: "personal" },
  { word: "GOD", category: "personal" },
  { word: "GOOD4U", category: "relationship" },
  { word: "LOVE4U", category: "relationship" },
  { word: "SPEEDY", category: "car-culture" },
  { word: "ILOVEU", category: "relationship" },
  { word: "DIE4U", category: "relationship" },
  { word: "BESTMOM", category: "family" },
  { word: "BESTDAD", category: "family" },
  { word: "GOAT", category: "aspirational" },
  { word: "PRETTY", category: "girly-cute" },
  { word: "CUTE", category: "girly-cute" },
  { word: "CUT", category: "girly-cute" },
  { word: "VETERAN", category: "military" },
  { word: "SNOOPY", category: "pop-culture" },
  { word: "BITCOIN", category: "misc" },
  { word: "F4ST", category: "car-culture" },
  { word: "B3STD4D", category: "family" },
  { word: "CUT3", category: "girly-cute" },
  // Batch 2 — added 2026-08-16
  { word: "KING", category: "aspirational" },
  { word: "QUEEN", category: "aspirational" },
  { word: "BOSS", category: "aspirational" },
  { word: "BIGBOSS", category: "aspirational" },
  { word: "LEGEND", category: "aspirational" },
  { word: "ICON", category: "aspirational" },
  { word: "LUCKY", category: "aspirational" },
  { word: "WINNER", category: "aspirational" },
  { word: "CHAMP", category: "aspirational" },
  { word: "HERO", category: "aspirational" },
  { word: "ELITE", category: "aspirational" },
  { word: "FAMOUS", category: "aspirational" },
  { word: "MVP", category: "aspirational" },
  { word: "2FAST4U", category: "car-culture" },
  { word: "RACER", category: "car-culture" },
  { word: "MAMA", category: "family" },
  { word: "DADDY", category: "family" },
  { word: "HACKER", category: "misc" },
  { word: "FAITH", category: "personal" },
  { word: "BELIEVE", category: "personal" },
  { word: "BLESSED", category: "personal" },
  { word: "PRAY", category: "personal" },
  { word: "HOPE", category: "personal" },
  { word: "GRACE", category: "personal" },
  { word: "AMEN", category: "personal" },
  { word: "THANKU", category: "personal" },
  { word: "MIRACL", category: "personal" },
  { word: "HEAVEN", category: "personal" },
  { word: "TRUST", category: "personal" },
  { word: "PEACE", category: "personal" },
  { word: "XOXO", category: "relationship" },
  { word: "KISSME", category: "relationship" },
  { word: "MYLOVE", category: "relationship" },
  { word: "LOVEME", category: "relationship" },
  { word: "PATRIOT", category: "military" },
];
